### ISSUE TITLE
How to concatenate multiple spans?

### ISSUE THREAD

**Issue by wajika** [equinix-labs/otel-cli#106]
My purpose is to use otel-cli to record the time-consuming of CI, then I can count if it's taking too much time. I keep trying multiple parameters, but according to the information I can find, it is impossible to combine multiple spans in otel-cli. I don't know if otel-cli can do this, if it works i want a demo to learn.

Let me illustrate with a picture:
![11](https://user-images.githubusercontent.com/17058349/155465894-861c63e1-d265-4d59-b016-263be7052cca.png)
Each arrow on the picture should be a span

------------------------------------------------------------

Another question, why command failed will not save the record to the error? Is it because elastic apm does not support it, or is the data format of otel-cli incompatible?

The event has been marked as failed, and the transaction result is an error. Is such a message an error? If it is, it should appear on the error UI, but the error UI is empty.
![1](https://user-images.githubusercontent.com/17058349/155466536-a770bdab-5adb-4cca-897d-5e11eb8fc8f3.png)
![2](https://user-images.githubusercontent.com/17058349/155466905-acb3e2d5-0b5b-4ddd-8e42-c3b99b50bf41.png)

event.outcome  => failure
transaction.result => error

**Comment by wajika** [comment]
@tobert hi can you explain?

**Comment by ahayworth** [comment]
Could you share any information about how you're recording spans in your CI suite? That may give us a little bit more information to help with - the picture was informative, but I think we need a little more information to understand what may be happening.

**Comment by wajika** [comment]
@ahayworth 
Hi. I describe my case.
I want to record the build process and count the time of each stage. After google search, I saw that the jenkins community provides an opentelemetry plugin. The data of the first picture is generated by the jenkins opentelemetry plugin, which satisfies my case.
But we mainly use the Azure devops pipeline to build (dotnet language), the azure community does not provide similar plugins, I want to use ote-cli to achieve the result like the first picture, after repeated testing, I have not found how to combine multiple events into a pipeline cycle , I hope to get some help or advice.

Our build process is like this:
![image](https://user-images.githubusercontent.com/17058349/156493186-d0ecd48d-bc5b-4458-8156-7abe9bb2e56a.png)

**Comment by tobert** [comment]
Apologies for being away. If I'm understanding your desire correctly, you would need to use the traceparent propagation via environment variables or the --tp-file option.

Please reopen if you're still at it and stuck.
