### ISSUE TITLE
Can not add attribute for background span

### ISSUE THREAD

**Issue by wolf666666** [equinix-labs/otel-cli#108]
Can not add attributes for background spans,
When you check the help command: otel-cli span background --help
the output example have the parameter: attr
but the command have no the attr.
After check the source code, there is no attr for span_background.go in line 56. it may should be similar with span.go
Could you fix it?

**Comment by tobert** [comment]
Hmm. I guess that would need another subcommand to make it work.

As it is now, you can only add attributes at the start and I didn't think about adding them while the span is open. I'll tag this for development.
