### ISSUE TITLE
environment variable OTEL_CLI_SERVICE_NAME and OTEL_CLI_ATTRIBUTES did not take effect

### ISSUE THREAD

**Issue by wolf666666** [equinix-labs/otel-cli#109]
When i set OTEL_CLI_SERVICE_NAME and OTEL_CLI_ATTRIBUTES with command line:
export OTEL_CLI_SERVICE_NAME="aaa" 
export OTEL_CLI_ATTRIBUTES="id=123"
It seems the two variable did not take effect when the span generated, but if i set them in the command line:
eg, otel-cli span --service aaa --attr "id=123", the two attributes will be add to the span

I think it may be a bug of otel-cli

**Comment by tobert** [comment]
Thanks for the report! I have a test in mind that I'll write first. I'm pretty swamped with work and other things and hope to work on this soon.

**Comment by tobert** [comment]
This was trickier to fix than I expected. Here's a PR, we'll merge soon. https://github.com/equinix-labs/otel-cli/pull/117

**Comment by tobert** [comment]
@wolf666666 thanks so much for the report. I feel embarrassed for leaving it like this so long but it's fixed now.

Please let me know if the latest code is working for you. I have a few more issues to work on then we'll get another release out.

**Comment by tobert** [comment]
This should be fixed permanently in release v0.1.0. Thanks for you patience <3

https://github.com/equinix-labs/otel-cli/releases/tag/v0.1.0
