### ISSUE TITLE
Minimal Go version should be >= 1.16?

### ISSUE THREAD

**Issue by andrewaylett** [equinix-labs/otel-cli#113]
Trying to install otel-cli on Debian Stable, which packages Go 1.15, I discovered that we use `os.WriteFile`, which was added in Go 1.16.

It's not altogether clear to me whether this is a bug in `go.mod`, which should list a higher minimum version of Go, or a bug in `server_json.go`, which shouldn't be using a function that doesn't exist in Go 1.14?

**Comment by tobert** [comment]
seems best to not use WriteFIle for now. https://github.com/equinix-labs/otel-cli/pull/115 will merge after reviews

**Comment by tobert** [comment]
The update to opentelemetry-go 1.11.2 in #138 forced go 1.18 anyways, so that's the minimum version now. Thanks for the report!
