### ISSUE TITLE
otel-cli exec in conjunction with background span and storing output to variable

### ISSUE THREAD

**Issue by BenB196** [equinix-labs/otel-cli#152]
Hi All,

I've been messing around with otel-cli for a bit (nice project btw), and I'm running into a bit of an issue with a script I'm trying to write and am wondering if anyone has any ideas.

Problem:

I want to use a background span and run otel-cli exec, but I also want to store the output of the command that exec runs as a variable for future use. But when I do this, I get an error.

Example:

```bash
#!/bin/bash

set -e
set -x

carrier=$(mktemp)
sockdir=$(mktemp -d)

otel-cli span background \
    --tp-carrier $carrier \
    --sockdir $sockdir \
    --tp-print \
    --service $0 \
    --name "$0 script execution" \
    --timeout 10 &

output=$(
    otel-cli exec --service $0 \
        --name "curl google" \
        --tp-required \
        --tp-carrier $carrier \
        --tp-print "curl https://google.com"
)

echo "${output}"
```

When I run this script though, I get the following error:

`failed to find a valid traceparent carrier in either environment for file '/tmp/tmp.TmpYvJyIKf' while it's required by --tp-required`

If I remove the variables storing part `output=$(...)`, the script works. Does anyone know how to achieve this?

**Comment by BenB196** [comment]
Just an update here, I don't actually think the issue is with `output=$(...)`, rather its an issue with the background job and bash not waiting long enough. If I run the above example a few times, occasionally it will work and sometimes it will fail. I suspect bash is running the second command before the first command can add the traceparent to `$carrier`. I'm not sure if anyone has any ideas on how to fix this. I know I could probably use something like `sleep`, but I'd like to avoid that if possible.

**Comment by tobert** [comment]
It's probably just running so fast that the carrier file hasn't been written yet by the time the second otel-cli tries to read it.

I think the solution will be to have --tp-carrier loop/sleep a few times to wait for the file. This might introduce latency for some folks but will probably be around 10-20ms in the common case. otel-cli span background does something similar for the Unix socket and it seems to work fine so we'll copy that approach.

**Comment by tobert** [comment]
@BenB196 I started a PR that adds a demo for 2 ways to handle this case, please let me know if it makes sense.
https://github.com/equinix-labs/otel-cli/pull/168/files

**Comment by BenB196** [comment]
Hi @tobert both examples look like they make sense (and are probably safer/more efficient than an uncontrolled infinite loop)

**Comment by tobert** [comment]
release v0.3.0, please reopen if there's still an issue

`otel-cli span background --wait` and the demo that shows how to avoid the condition is included in that release.
