### ISSUE TITLE
Default HTTP port doesn't align with spec

### ISSUE THREAD

**Issue by jmorrell** [equinix-labs/otel-cli#157]
Hi! 👋 

Unless I'm missing something, according to the spec there are different default ports for `grpc` and `http` protocols: https://opentelemetry.io/docs/concepts/sdk-configuration/otlp-exporter-configuration/#otel_exporter_otlp_endpoint

> Default value:
> 
> gRPC: "http://localhost:4317"
> HTTP: "http://localhost:4318"

Without any configuration `otel-cli` defaults to sending HTTP protocol to `http://localhost:4317` instead of `http://localhost:4318`. I would expect that endpoint if the default protocol were grpc.

You can see the default values for the collector per-protocol here as well: https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md#getting-started

It's a small, tedious thing, but we're running into it when trying to use `otel-cli` with [otel-desktop-viewer](https://github.com/CtrlSpice/otel-desktop-viewer#example-with-otel-cli), and it would be nice if all the defaults could work together without further configuration

**Comment by tobert** [comment]
You are correct. I'll fix it up this week. I have a few things to throw into a v0.1.1 release anyways so we'll get that out too.

**Comment by tobert** [comment]
Also, TIL about otel-desktop-viewer. Cool!!!!

If you feel ambitious, I wouldn't mind replacing the docker-compose setup in otel-cli with otel-desktop-viewer :)

**Comment by tobert** [comment]
I started looking into this, and in the current version of otel-cli doesn't default an endpoint at all. When no envvar or `--endpoint` param are provided, otel-cli goes into non-recording mode. This is so folks can put otel-cli in scripts without any configuration and enable/disable it as needed without breaking things.

Please let me know if I'm missing something.

**Comment by jmorrell** [comment]
oh, I must have mis-interpreted what I was seeing 😅 . I think that that makes sense as a design decision given how folks are likely using this tool so I'll close this. Thank you for looking into it!
