### ISSUE TITLE
Would like to set TraceID and SpanID

### ISSUE THREAD

**Issue by ham1** [equinix-labs/otel-cli#173]
We are trying to use this for a complex build pipeline, it works inside jobs (we create a known root span ID and trace ID and then set TRACEPARENT at the start of each job)
However, we can't find a way to send the root span at the end of the pipeline.
If we could specify the trace ID and span ID then this would work for us.
Thank you!

**Comment by tobert** [comment]
🤔 This will be a little tricky because opentelemetry-go (by way of the specs) makes it difficult to set your own trace/span id. I like the idea though and will try a few things next week.

**Comment by wushujames** [comment]
I think it's possible to provide your own ID generator. 

https://github.com/open-telemetry/opentelemetry-go/blob/6a95d5770c347859d7b71dc660361f875f3d44fb/sdk/trace/tracer.go#L89

**Comment by tobert** [comment]
The PR linked is where I think I will end up, but also I tracked down how to configure the idGenerators. It's a viable approach but also a hack which is why I'm considering the direct-to-protobuf PR in #175.

https://github.com/open-telemetry/opentelemetry-go/blob/6a95d5770c347859d7b71dc660361f875f3d44fb/sdk/trace/provider.go#L329

**Comment by ham1** [comment]
I can see a lot of work on the PR, so thank you, just wanted to check if you had an ETA for this as we'd love to use this feature.
Thank you!

**Comment by ham1** [comment]
I noticed the PR #175 has been merged, does this now solve this issue?
If so, how and can we please have a release, if not, what more needs doing? We might have some time to help with another PR.

**Comment by tobert** [comment]
Looks like adding a command-line flag to span.go and conditions to `NewProtobufSpanWithConfig()` https://github.com/equinix-labs/otel-cli/blob/e0426f87d40aca553b3ad70243ac78fe176abe20/otelcli/protobuf_span.go#L107.

this seems ok:
`otel-cli span --span-id ${span_id} --trace-id ${trace_id} --name "root trace" --start "${start_time}" --end "${end_time}"`
or should it be a bit more explicit?
`otel-cli span --force-span-id $span_id`??? Dunno if I like it. otel-cli users know wtf they're doing usually. OTel spec doesn't like allowing it. But otel-cli has to make a lot of compromises anyways.

**Comment by ham1** [comment]
That's great, thank you. Should we add some examples to the README and add them to the table of arguments?

**Comment by tobert** [comment]
release v0.3.0, please reopen if there's still an issue
