### ISSUE TITLE
pull requests stalled

### ISSUE THREAD

**Issue by tobert** [equinix-labs/otel-cli#183]
I am considering asking the equinix-labs admins to disable the policy that requires someone not-me approve all pull requests. I've had some PRs sit a while because nobody's available to review. Mostly I've been reviewing my own PRs by waiting a while and coming back to them.

Alternatively, if a couple folks volunteer to be reviewers, I will figure out how to get you added to the list and we can continue with a normal PR process.

**Comment by garthk** [comment]
I'm attempting a dependency on otel-cli, and will be happy to review PRs if I succeed. That said I'd also be trying to facilitate custom distributions with extra processors and exporters, which might be more than you're up for.

**Comment by tobert** [comment]
Happy to have the eyes! I'll have a PR for envvar propagation in the next
few days.

Tell me more about the various exporters? I kinda want to write custom ones
anyways so I'm interested.

-Amy

**Comment by garthk** [comment]
If we squint hard enough `otel-cli` kinda resembles the OpenTelemetry Collector? One could argue the same of anything that creates or receives, processes, and exports telemetry, but that's kinda my point.

One opportunity allowed by the resemblance is replacing the custom code for representing and exporting spans with OTC's [pdata](https://github.com/open-telemetry/opentelemetry-collector/tree/main/pdata) and [exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter) packages. Crummy timing vs #175 sorry, but I didn't put all this together until just now.

You could also use OTC's [config](https://github.com/open-telemetry/opentelemetry-collector/tree/main/config) to load the exporter configuration from YAML. Or, given it wants you to [configure your environment variables in the YAML](https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables) to use their [envprovider](https://github.com/open-telemetry/opentelemetry-collector/tree/main/confmap/provider/envprovider), maybe not.

I think the temptation to use OTC's receivers and the [otel-desktop-viewer](https://github.com/CtrlSpice/otel-desktop-viewer/) exporter/GUI for `otel-cli server` is a bit of a trap. After hooking them together with OTC's pipelines and processors you'll have a hand-crafted [custom distribution of the Collector](https://opentelemetry.io/docs/collector/distributions/) on your hands. I think it'd be more practical to remove the server, extract its TUI to an OTC exporter component like the web app, and direct users to pack their own TUI/GUI distro. A red diff is a good diff! And, then I'd advise cashing in your winnings. But, what if you felt like doubling down, instead?

I bet if you looked at OCB's output you could figure out how to add an `exec` command to the OpenTelemetry Collector.

**Comment by garthk** [comment]
I'm sorry, all that extrapolation about what happens when you support OTC components was besides the point and didn't answer your question. 

I'm interested in configuring an exporter to spool traces to disk. It'll help deal with a few scenarios in which I can't assume connectivity, either from the CLI to the Collector or from the Collector onward.

**Comment by tobert** [comment]
Buffer to disk is doable and was on my mind when I wrote `otel-cli server
json`. We could add a `otel-cli server protobuf` with a similar fs tree of
proto files to preserve types. Then write a "player" that shoots them over
otlp. The player idea could also be useful to let folks write out proto or
json files and just have otel-cli do the sending part.

Seems doable even if I switch to my own exporter. flock() across processes
should be fine for most cases. Most of the code is already there.

Neat idea!

**Comment by tobert** [comment]
I'm approving my own PRs but still going through the process for transparency. If/when folks show up to do reviews for me I'll be happy to have the help, but for now, this keeps things moving.
