### ISSUE TITLE
exec sends zero-length spans

### ISSUE THREAD

**Issue by garthk** [equinix-labs/otel-cli#189]
`doExec` needs to update the span's end time after calling `child.Run`. This does the trick but could be extracted for testing purposes:
```go
    span.EndTimeUnixNano = uint64(time.Now().UnixNano())
```
Speaking of testing, if this was introduced in #175 without getting caught it suggests a gap in test coverage.

**Comment by tobert** [comment]
Good catch, I'll add a test and fix it soon.

**Comment by tobert** [comment]
Should be fixed on main. Thanks for the report!

**Comment by tobert** [comment]
release v0.3.0, please reopen if there's still an issue
