### ISSUE TITLE
OTEL_EXPORTER_OTLP_ENDPOINT treatment not following spec

### ISSUE THREAD

**Issue by mechie** [equinix-labs/otel-cli#200]
See the [Protocol Exporter doc](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#endpoint-urls-for-otlphttp):
> If signals are sent that have no per-signal configuration from the previous point, OTEL_EXPORTER_OTLP_ENDPOINT is used as a base URL and the signals are sent to these paths relative to that:
> - Traces: `v1/traces`

Fairly sure the issue is [here](https://github.com/equinix-labs/otel-cli/blob/f47323e4727626b7de1be33e4d3ba0a79282a4d8/otelcli/otlp_client.go#L203):
```golang
if endpointURL.Path == "" {
	// Per spec, /v1/traces is the default:
	// (https://github.com/open-telemetry/opentelemetry-specification/blob/c14f5416605cb1bfce6e6e1984cbbeceb1bf35a2/specification/protocol/exporter.md#endpoint-urls-for-otlphttp)
	endpointURL.Path = "/v1/traces"
}
```
This contradicts [Example 3](https://github.com/open-telemetry/opentelemetry-specification/blob/c14f5416605cb1bfce6e6e1984cbbeceb1bf35a2/specification/protocol/exporter.md#example-3) in the spec:
> ```sh
> export OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4318/mycollector/
> ```
> Traces are sent to http://collector:4318/mycollector/v1/traces

`otel-cli` will instead try sending the traces to `http://collector:4318/mycollector`, as the path is not empty. The collector I was sending traces to has a non-empty path in its URL, so this led to a bit of confusion.

Easy enough for us to work around it by giving the trace URL to `otel-cli`, but this is probably going to surprise other folk.

Unsure how this can be fixed without a breaking change (even if it's arguably a bug), hence bringing it up for discussion instead of trying to PR directly.

**Comment by tobert** [comment]
TBH I've had a hard time understanding the nitpicking in that part of the spec. If you think you understand how it should be, please do send a PR. It likely won't break anyone and I agree it's best to stick with the spec. Getting this right will probably also help with adding metrics & logs someday too.

**Comment by tobert** [comment]
@mechie please take a look at #214 if you have a moment

**Comment by mechie** [comment]
LGTM! Meant to take a stab at this last week but things have been hectic on my end, thank you for taking it on.

**Comment by tobert** [comment]
release v0.3.0, please reopen if there's still an issue
