### ISSUE TITLE
Export Otel-Cli generated traces and metrics to openTelemetry  collector deployed in an docker or Kubernetes (containerised) env

### ISSUE THREAD

**Issue by sujaymahesh4** [equinix-labs/otel-cli#218]
I am not able to export  Otel-Cli generated traces and metrics to openTelemetry  collector deployed in an docker or Kubernetes  setting the export OTEL_EXPORTER_OTLP_ENDPOINT variable . 
I am able to  export the same to a otelCollector deployed as a binary on local Host . 

Is there any more changes we need to do in order to export the data from the otel-cli running on local to a openTel collector running on a containerised environment .

**Comment by tobert** [comment]
It should be fine in containers and I believe lots of folks are using it in Kubernetes.

Can you try `otel-cli status` and grab the output? Please check it over for sensitive info and post it if you can.

**Comment by sujaymahesh4** [comment]
hey @tobert Thanks for the clarification . 

So if i add --endpoint=http://{{containerNAME}}:4318 , the trace endpoint is being updated to https://{{containerNAME}}:4318/v1/traces . 

I have also set OTEL_EXPORTER_OTLP_INSECURE to false . 

It is adding http(s) by default . and the open telemetry collector is returning 

Getting this error : 
OpenTelemetry error: traces export: Post "https://={{containerName}}:4318/v1/traces": http: server gave HTTP response to HTTPS client

**Comment by sujaymahesh4** [comment]
{
    "config": {
        "endpoint": "",
        "protocol": "",
        "timeout": "1s",
        "otlp_headers": {},
        "insecure": false,
        "otlp_blocking": false,
        "tls_ca_cert": "",
        "tls_client_key": "",
        "tls_client_cert": "",
        "tls_no_verify": false,
        "service_name": "otel-cli",
        "span_name": "todo-generate-default-span-names",
        "span_kind": "client",
        "span_attributes": {},
        "span_status_code": "unset",
        "span_status_description": "",
        "traceparent_carrier_file": "",
        "traceparent_ignore_env": false,
        "traceparent_print": false,
        "traceparent_print_export": false,
        "traceparent_required": false,
        "background_parent_poll_ms": 10,
        "background_socket_directory": "",
        "background_wait": false,
        "background_skip_parent_pid_check": false,
        "span_start_time": "now",
        "span_end_time": "now",
        "event_name": "todo-generate-default-event-names",
        "event_time": "now",
        "config_file": "",
        "verbose": false,
        "fail": false
    },
    "span_data": {
        "is_sampled": "false",
        "span_id": "0000000000000000",
        "trace_flags": "00",
        "trace_id": "00000000000000000000000000000000"
    },

"diagnostics": {
        "cli_args": [
            "status"
        ],
        "is_recording": false,
        "config_file_loaded": false,
        "number_of_args": 1,
        "detected_localhost": false,
        "insecure_skip_verify": false,
        "parsed_timeout_ms": 0,
        "otel_error": "",
        "exec_exit_code": 0
    }
}

**Comment by sujaymahesh4** [comment]
hey [@tobert](https://github.com/tobert) Thanks for the clarification .
So if i add --endpoint=http://{{containerNAME}}:4318 , the trace endpoint is being updated to https://{{containerNAME}}:4318/v1/traces .
I have also set OTEL_EXPORTER_OTLP_INSECURE to true .
It is adding http(s) by default . and the open telemetry collector is returning
Getting this error : OpenTelemetry error: traces export: Post "https://={{containerName}}:4318/v1/traces": http: server gave HTTP response to HTTPS client
