### ISSUE TITLE
Expose GRPC connection status information

### ISSUE THREAD

**Issue by mterhar** [equinix-labs/otel-cli#226]
GRPC is a difficult protocol to troubleshoot so there doesn't seem to be a tool that enables this sort of inspection today. The otel-cli looks to be close. 

The main use case is validating configuration of load balancers in front of GRPC servers (Otel Collector, Refinery, etc)

Example cli command: `otel-cli status --keepalive 1 --verbose --fail`

An output that has something like: 

* connection established with a timestamp
* an output for each recoverable error with a timestamp
* an attempt to reconnect?

Initial idea was to add a `keepalive` flag and verbose level log output to `processGrpcStatus` function: https://github.com/equinix-labs/otel-cli/blob/bdbfcbb684cedba9f3846135adf06f4937616a90/otlpclient/otlp_client_grpc.go#L98

**Comment by tobert** [comment]
I took a look at scope and decided to draft #227. Adding context through the OTLP client probably isn't fair to ask of a new contributor so I got that taken care of. In the process I found a few flaws in otel-cli's OTLP client code and fixed them. As a result, the OTLP client is more correct now.

I also added a first pass at the --keepalive we talked about so @mterhar can kick the tires.

A TODO is to figure out how to test that different gRPC strategies result in the right behavior. The current test framework and otlpserver don't make this easy but it needs to be done if only so the otlpclient can be tested more deeply.

I'm gonna sleep on the PR over the weekend and come back to it with fresh eyes and touch up.

**Comment by tobert** [comment]
🤔 after sleeping on the PR, I don't really like "--keepalive", might rework it to "--span-count" and "--spread-ms" or something like that. Gonna think about it today and noodle on some ideas.

**Comment by tobert** [comment]
Went with `otel-cli status --canary-count 1 --canary-interval 10ms`.

Is the error text sufficient for your needs @mterhar? There's an example in #227's conversation.

**Comment by tobert** [comment]
I merged #232 so gRPC headers should work correctly now. Tests pass, they're here: https://github.com/equinix-labs/otel-cli/blob/main/data_for_test.go#L958

**Comment by tobert** [comment]
The functionality inspired by this issue was merged a while ago. Please reopen or create a new issue if you have further needs.
