### ISSUE TITLE
Feature Request: Add a flag for `--force-parent-span-id`

### ISSUE THREAD

**Issue by domofactor** [equinix-labs/otel-cli#240]
Hey there 👋 

Similar to how there's currently functionality for `--force-trace-id` and `--force-span-id`, i'd like to request a feature for `--force-parent-span-id`. The use case here would be useful for folks such as myself that are interested in creating traces with child spans across different languages. 

For example, starting a trace w/ parent spans in Ruby OpenTelemetry and passing those parent span ids down into a Bash script with otel-cli so there's a complete trace.

Any input/thoughts would be appreciated, Thanks!

**Comment by tobert** [comment]
I'm happy to add the feature, makes sense.

Also, did you try setting a TRACEPARENT environment variable before calling otel-cli? otel-cli allows propagating traceparent over envvar and files and that should get your parent trace set automatically.

**Comment by domofactor** [comment]
@tolbert yeah, unfortunately it looked like TRACEPARENT allowed me to overwrite the trace-id and span-id itself, but not trace-id + parent-span-id like I required for making all otel-cli's spans be child spans. 

I may have missed something though, so feel free to let me know if that's not the case 😄

**Comment by tobert** [comment]
If you set TRACEPARENT, usually otel-cli will set your parent span id to the span in the traceparent. It's very similar to how things work over http/grpc headers with the `traceparent` header.

**Comment by tobert** [comment]
PR merged, thank you! I'll close this once I release.

**Comment by domofactor** [comment]
@tobert sounds great, thanks! any idea roughly what the ETA of the next release is?

**Comment by tobert** [comment]
@domofactor apologies, I disappeared into a huge project for a bit. I think the new OTLP work is settled enough to release. I'll do it in the next week or so.

**Comment by tobert** [comment]
I released v0.4.0 yesterday. Please open more issues if you run into trouble!
