### ISSUE TITLE
Question about configuration override order

### ISSUE THREAD

**Issue by parsonsmatt** [equinix-labs/otel-cli#257]
The README specifies:

```
All three modes of config can be mixed. Command line args are loaded first,
then config file, then environment variables.
```

And, indeed, it seems like environment variables overwrite CLI arguments. Somewhat surprisingly, this means that a script like:

```sh
$ export OTEL_SERVICE_NAME='foobar'
$ otel-cli exec --service-name cool -- sleep 10
```

will report a span with `service.name` of `foobar`.

I feel like I generally see a convention of "local takes precedence over global," usually with command-line flags overriding environment variables, and env vars overriding configuration files, and local config files overriding global ones. [At the very least, one guideline agrees with this intuition, so I'm not the only one](https://clig.dev/#configuration). 

I'm curious what the rationale may be for having CLI options being overridden by config file and environment variables?

**Comment by parsonsmatt** [comment]
Our work repository has a `.envrc.sample` that sets flags to report traces during local development and our test suite - one of these is `OTEL_SERVICE_NAME=backend`. I'm extending our tracing to instrument local build/test/workflows, so I can get better insight into improving our developer experience. However, I don't want `otel-cli` to use the `backend` service name - I'd prefer it to use something like `local-dev-workflow` to disambiguate.

So, in our `Makefile`, I have something like this:

```
build:
    otel-cli exec --service-name cool --span-name "build" -- $(CABAL) build

watch:
    otel-cli exec --service-name watch --span-name "watch" -- watch make build
```

`otel-cli` picks up the `OTEL_SERVICE_NAME` in the environment and overrides the `--service-name` parameter.

As a work-around, I can do:

```
build:
    OTEL_SERVICE_NAME="local-dev" otel-cli exec --span-name "build" -- $(CABAL) build
```

But this work-around requires some finagling with environment variables when I go to instrument our tests, which *do* use the `backend` service name:

```
test:
    OTEL_SERVICE_NAME="local-dev" otel-cli exec --span-name "test" -- OTEL_SERVICE_NAME=$(OTEL_SERVICE_NAME) $(CABAL) test
```

**Comment by tobert** [comment]
I've been thinking about this. There isn't an easy solution right now, but I think it's a good idea to improve the situation for your use case.

I could make envvars load before command-line args. Config file will have to load last since it's specified in either envvar or CLI so otel-cli can find it. I'll think on this more and the impact of change on other otel-cli users. I suspect it'll be fine but want to consider it more.

**Comment by tobert** [comment]
Gonna close this for now. Happy to revisit if a use case comes up that the current configuration order prevents.
