### ISSUE TITLE
`otel-cli exec` does not report a span if the command failed

### ISSUE THREAD

**Issue by parsonsmatt** [equinix-labs/otel-cli#258]
```sh
$ otel-cli exec -- false
```

The above example does not report a span. If I run with `--verbose`, then I see this:

```sh
$ otel-cli exec --verbose -- false
2023/08/30 18:36:07 command failed: exit status 1
```

I think the issue is [here](https://github.com/equinix-labs/otel-cli/blob/5f1223a809007b088af2ea9b9c534a798589f1f4/otelcli/exec.go#L96-L99):

```go
	if err := child.Run(); err != nil {
		config.SoftFail("command failed: %s", err)
	}
	span.EndTimeUnixNano = uint64(time.Now().UnixNano())

	ctx, err := otlpclient.SendSpan(ctx, client, config, span)
	if err != nil {
		config.SoftFail("unable to send span: %s", err)
	}
```

Calling `config.SoftFail` is going to exit immediately. What is probably intended instead is to record the span with an error code.

**Comment by tobert** [comment]
Yep, the first config.SoftFail is the problem. My bad. If we get the test in your PR working, it'll make sure this doesn't revert.
