### ISSUE TITLE
`otel-cli exec` does not report a span when `SIGINT` is passed

### ISSUE THREAD

**Issue by parsonsmatt** [equinix-labs/otel-cli#261]
```shell
$ otel-cli exec -- sleep 100
^C
```

Currently, `otel-cli` handles this by dying.

The scenario I'm observing this is that I have a file-watcher program that runs `make build` whenever any relevant files change. I've instrumented `make build` to do a span, and `make watch` also. The only way to exit the filewatcher is to `<Ctrl-C>` it from the terminal, but this also kills `otel-cli`, so the `make build`s are reported with an empty/missing parent span.

**Comment by tobert** [comment]
Good catch, and someone else asked before. It makes sense to add a flag to otel-cli like `--ignore-signals` or `--ignore-sigint` perhaps. Might be cool to have SIGHUP send a span event. I'll keep this open and work on it as a feature/bugfix for the next release.

**Comment by tobert** [comment]
0.4.1 is released and the issue should be solved. Please reopen if the issue persists.
