### ISSUE TITLE
Protocol error (directions?‚

### ISSUE THREAD

**Issue by jeeftor** [equinix-labs/otel-cli#305]
`otel-cli exec --protocol http --verbose --endpoint localhost:4318 --service test --name "ip" curl  ifconfig.me`

>136.226.7.712024/02/20 10:52:39 invalid protocol setting "http"

**Comment by tobert** [comment]
I think you need `--protocol http/protobuf`. I'll consider adding a plain `http` option since that seems pretty obvious.
