### ISSUE TITLE
add functional tests

### ISSUE THREAD

**Issue by tobert** [equinix-labs/otel-cli#34]
By functional tests I mean something that takes a build of otel-cli and runs the binary to exercise the code paths.

The shell scripts in the `demos` directory is a good place to start. I use them to test binaries locally but they're not really automatable in their current form.

TODO:
- [ ] identify a good framework for CLI tool testing
- [ ] stub OTLP server that dumps spans to a json file (maybe another fun/useful project?)
- [ ] write tests

**Comment by tobert** [comment]
easiest OTLP server API: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver

**Comment by tobert** [comment]
@ahayworth do you know what's hot for testing (Go) CLIs?

There are a few TAP protocol shell testing harnesses but I'm not convinced that's the right call: https://testanything.org/producers.html#shell

**Comment by ahayworth** [comment]
I can't say I've written tests for a go cli recently (the last time I did - you and I were still working at the same place, so it's been a few minutes to say the least).

If you're looking for end-to-end functional tests, I personally think TAP is alright.

**Comment by tobert** [comment]
working on the server here: https://github.com/packethost/otel-cli/pull/35

**Comment by tobert** [comment]
@emattiza re: https://github.com/equinix-labs/otel-cli/issues/70#issuecomment-916407139

gonna do it like this: https://github.com/equinix-labs/otel-init-go/tree/main/cmd/test-otel-init-go (this can get better now that otel-cli/otlpserver is a separate package those tests can import themselves)

The OTLP server and `otel-cli status` were leading here. Now the test harness runs just otel-cli status for the bulk of the config tests and it can all be organized into json fixtures. I might be tempted to switch to yaml but otel-cli already imports json so it feels like the right choice.

**Comment by tobert** [comment]
#79 merged, there's more to do but we can do that organically. Closing :)
