### ISSUE TITLE
document contribution and release processes

### ISSUE THREAD

**Issue by tobert** [equinix-labs/otel-cli#39]
Since a bunch of folks seem to be using otel-cli in their work, it's probably time we get serious about consistent release process and actually doing PR approvals.

I've been merging PRs to move things along towards a 0.1.0 release, but that shouldn't continue if others are relying on this. I'd also like to add some maintainers, starting with @ahayworth and see who else volunteers.

Sortof unrelated but we (Equinix Metal) might migrate this repo over to one of our dedicated OSS GitHub organizations soon. That will hopefully make the provenance and status of otel-cli a little clearer, and give it a long-term home.

**Comment by tobert** [comment]
@cyrille-leclerc @ahayworth I'd love to hear your thoughts. I'm leaning towards a pretty typical GitHub/OSS workflow, especially as we get more contributors in here.

**Comment by ahayworth** [comment]
@tobert I'd be delighted to help! Although, I'm not really using it day-to-day at the moment. But if I can share the load, I'd be glad to!

**Comment by tobert** [comment]
https://github.com/equinix-labs/otel-cli/releases/tag/v0.0.5 released with more packages and adjustments to goreleaser.

Gotta figure out how to make those changelogs nicer.

**Comment by tobert** [comment]
I added some docs to the README a while ago. Gonna open a new issue about automating releases.
