### ISSUE TITLE
add support for command-line completion

### ISSUE THREAD

**Issue by tobert** [equinix-labs/otel-cli#57]
We're already using Cobra and it can auto-generate the completions with a little work. Some folks might like this? Also seems like a straightforward issue with low risk for someone new to otel-cli to pick up.

Bonus points: add these to the OS packages

https://github.com/spf13/cobra/blob/master/shell_completions.md

**Comment by ahayworth** [comment]
Shell completions are always super nice! I don't know if homebrew packages support it in a clean way, so we might be stuck there. But we should provide them wherever we can! :)
