### ISSUE TITLE
customize help text for subcommands

### ISSUE THREAD

**Issue by tobert** [equinix-labs/otel-cli#65]
/cc #57 and #64 

I took DRY a little too far with some of the arguments to subcommands and wrapped them up in reusable functions in cmd/root.go.  This works ok but means some of the help text is too generic, and some are just wrong.

- [ ] review subcommand arguments and copy flags local as needed
- [ ] do a pass over all the help text and make sure it's as clear as possible while keeping the output terse
- [ ] make sure all required subcommand arguments have custom and clear help text

**Comment by tobert** [comment]
@emattiza does this look like I understood your comment in #64 correctly?

**Comment by emattiza** [comment]
yup, this scopes it down. mostly it's questions about options and flags, particularly when folks are using this via env-vars and won't use options/flags at all.
