### ISSUE TITLE
OTEL_EXPORTER_OTLP_ENDPOINT is not working

### ISSUE THREAD

**Issue by tobert** [equinix-labs/otel-cli#70]
I am looking into it and will get it fixed and release v0.0.15 ASAP. I am also going to prioritize those tests that would prevent this.

OTEL_EXPORTER_OTLP_ENDPOINT and presumably other envvars are not working. This is probably because of something I did in https://github.com/equinix-labs/otel-cli/commit/70f5bd4437be4669c64181984b4fc27499eebddc

My bad,
-Amy

**Comment by tobert** [comment]
this should work and does not:
env -i OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317 PATH=/bin ./otel-cli status`

this does work, so at least --endpoint is working:
`env -i OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317 PATH=/bin ./otel-cli status --endpoint localhost:4317`

**Comment by tobert** [comment]
I could swear these worked just last week but looking more into the code it appears I've always had the argument order for `viper.BindEnv()` backwards!? I am somewhat tempted to drop viper for now.

**Comment by emattiza** [comment]
Yeah that is kind of funky for that function interface but who am i to comment on that. Wanted to paste this here as this shows the debug output, and think this may be helpful in making sure the argument order is correct. 
![image](https://user-images.githubusercontent.com/11719476/132734367-b508dfad-ce14-4490-86aa-b68c599f8d58.png)
Here is the internal v.env after insertion to the env map
![image](https://user-images.githubusercontent.com/11719476/132734815-04ca103a-5b4d-47e2-81bf-ca550dbaaba5.png)

**Comment by tobert** [comment]
Nice! Yeah I just found that particular problem but fixing it does not fix envvar loading for me. I'll push those up in a PR in a few just so that's out of the way.

As far as I can tell envvars never worked in otel-cli and I didn't notice because I mostly used the old default endpoint.

I've tried a dozen variations and still haven't figured this out...

**Comment by tobert** [comment]
Huge thank you (again) to @emattiza :)

```sh
go build && env -i PATH=/bin OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317 ./otel-cli status
```

```js
{
    "config": {
        "endpoint": "localhost:4317",
        "timeout": "1s",
        "headers": {},
        "insecure": false,
        "blocking": false,
        "no_tls_verify": false,
        "service_name": "otel-cli",
        "span_name": "todo-generate-default-span-names",
        "span_kind": "client",
        "span_attributes": {},
        "traceparent_carrier_file": "",
        "traceparent_ignore_env": false,
        "traceparent_print": false,
        "traceparent_print_export": false,
        "traceparent_required": false,
        "background_parent_poll_ms": 10,
        "background_socket_directory": "",
        "span_start_time": "",
        "span_end_time": "",
        "event_name": "todo-generate-default-event-names",
        "event_time": "now",
        "config_file": ""
    },
    "span_data": {
        "is_sampled": "true",
        "span_id": "4b1b8c92fc112576",
        "trace_flags": "01",
        "trace_id": "0e05c1844d3526cb8431298fb4103761"
    },
    "env": {
        "OTEL_EXPORTER_OTLP_ENDPOINT": "localhost:4317",
        "PATH": "/bin"
    }
}
```

**Comment by tobert** [comment]
I'm gonna keep this open until I write the tests for envvars. I think we might need to do more mapping for the unmarshal to convert dashes to underscores. I saw some stuff about that in the docs.

**Comment by tobert** [comment]
actually no, I'll tack that onto the testing and otel env spec issues, both of which I want to knock out asap

**Comment by emattiza** [comment]
were you still going to use a external shell test tool like a [shellspec](https://github.com/shellspec/shellspec) or go native go e2e test?

**Comment by tobert** [comment]
released v.0.0.15 with fixes wrapped in. closing. https://github.com/equinix-labs/otel-cli/releases/tag/v0.0.15
