### ISSUE TITLE
Optimize Dependency size through replacing Viper

### ISSUE THREAD

**Issue by emattiza** [equinix-labs/otel-cli#82]
Just a tracking issue to look at alternative config libs like [koanf](https://github.com/knadh/koanf) that have a smaller dependency tree and may be better choices. We can also look at a raw approach to really get lean on dependencies.

For koanf compared to Viper:
- [Lower binary size and dependency tree](https://github.com/knadh/koanf/wiki/Comparison-with-spf13-viper)
- [Other optimizations](https://github.com/knadh/koanf#alternative-to-viper)

For raw Go and no deps;
- Just stdlib, but lots of plumbing and maybe a json encoding dependency.
- So as small as it gets!

**Comment by tobert** [comment]
I'm not a big fan of these libraries that support >1 config format. It adds a ton of bug and UX surface for debatable value.

With the refactors I've done in #79 I think it'll be straightforward to drop Viper and use straight encoding/json and os.Getenv. It's not a ton of code so it feels like the dependency isn't buying us much.

**Comment by tobert** [comment]
Sorry, I think this is still a useful issue! Did I miss a goal?

**Comment by emattiza** [comment]
No, its perfect! Going to recreate as a separate issue for tracking taking it to os.Getenv and json encoding, but had to drop for a call and havent gotten to it yet.
