### ISSUE TITLE
Weird interaction with fish

### ISSUE THREAD

**Issue by agracey** [equinix-labs/otel-cli#98]
First off, this tool is amazing and has already helped me solve multiple issues! Also, your code is nicely readable even by someone like me who really dislikes golang!

In fish, if I run without the timeout specified, the span doesn't write to the collector and the program returns shortly with an exit code of 0 (even with the &). This stumped me for a while until I found that setting the timeout to some very high number does exactly what I need. 

I've confirmed that the same command that breaks in fish work flawlessly when I switch to bash without any other env change. Which is weird... I wonder if fish does some extra fork/redirection?

**Comment by tobert** [comment]
Oh interesting. I'll mark this a bug and see if I can reproduce.

In the mean time, if you get a chance, please try again with the `--verbose --fail` flags? By default otel-cli tries really hard to not return error codes or do anything that would make e.g. `set -eo pipefail` users have a bad time.

**Comment by tobert** [comment]
Timeout code has changed a lot since this issue. Please re-open if it's still a problem.
