### ISSUE TITLE
brew warning about bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by puckpuck** [equinix-labs/otel-cli#99]
When otel-cli is installed on MacOS using brew, you get this warning message when you do a brew install or brew upgrade

```
√ ~ 🤘 : brew upgrade
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the equinix-labs/otel-cli tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/equinix-labs/homebrew-otel-cli/otel-cli.rb:10
  ```

**Comment by ahayworth** [comment]
@puckpuck Thank you! There is an open PR for this on the homebrew tap repo: https://github.com/equinix-labs/homebrew-otel-cli/pull/2

Once that's merged (and, I think, after the next otel-cli release) that warning should go away.

**Comment by tobert** [comment]
Merged that. I'll also need to make sure I update goreleaser before next release, so I'll leave this open for now.

**Comment by tobert** [comment]
I've release v0.1.0 with latest goreleaser so this should be sorted.

https://github.com/equinix-labs/otel-cli/releases/tag/v0.1.0
